
# Site settings
title: "Alexander Lalejini"
email: amlalejini@gmail.com

include:
  - _pages

sass:
  sass_dir: _sass

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
    
plugins:
  - jekyll-sitemap